src/Memcached.h

Older version of libmemcached on RHEL6 requires one extra typedef.

Fixed compiling with older libmemcached on RHEL6

---

configure.in

Previously, compiling IIP with Kakadu 7.5+ would result in a failed build due to symbols being referenced but not found.
The problem was that since Kakadu 7.5 the necessary symbols have been separated out into their own files which were not included in the IIP build script.
The workaround was to disable SSSE3 and AVX2 in the Kakadu build scripts.
This commit fixes this problem by adding the necessary files to the build script by detecting their presence in the `apps/make` directory first. If `avx2_stripe_transfer.o` is not present, the Kakadu version is assumed to be less than 7.5; otherwise it's assumed to be >= 7.5
See: https://groups.yahoo.com/neo/groups/kakadu_jpeg2000/conversations/messages/7071
Tested on Kakadu 7.3.1, 7.4, 7.5, 7.6
Fixes #35

Fixed: IIP Compiles with AVX2 and SSSE3 extensions

---

ChangeLog
README
autogen.sh
doc/doxygen-html.conf
src/IIPImage.h
src/KakaduImage.cc
src/TPTImage.cc
src/Task.cc
src/View.cc
windows/unified installers/iipimage_IIS_x86_x64.iss

All of them were found using codespell.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Fix typos in documentation, code comments and messages

---

src/IIPImage.cc

Adding 'static const' reduces the code size.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

Optimize code for file signatures

---

src/Main.cc

In my application I use Nginx to access cluster of IIPImage servers via FastCGI unix sockets. I tried to stress test my application and figured out that IIPImage servers respond with "...11: Resource temporarily unavailable..." at quite low traffic – around 40 parallel users. After few hours of investigation I found that backlog size is hardcoded as 10 which is quite low for highly loaded applications. I changed it to 2048 and recompiled. Now my application is able to withstand 1000 concurrent users. Probably it would be better to push this value as a parameter.

FastCGI socket backlog size increased to withstand higher load.

---

src/IIIF.cc
src/Main.cc

This commit makes two small fixes to the IIIF info.json response.
1) If REQUEST_URI is not set on the FastCGI request, the server will raise an invalid_argument error, since the required `@id` parameter for the IIIF request could not be set.
2) A new session header is stored that checks the HTTPS FastCGI header. If it is present, it will ensure this scheme is reflected in the IIIF JSON info.json response. This is to prevent the situation where an info.json request is only available via https, leading the info.json to reflect an incorrect location for the image.

Small fixes to IIIF info response.

---

configure.ac

* Add spaces to align the text columns.
* Start the text for '--enable-debug' with lower case.
* Use uniform case for 'Kakadu' in all messages.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

configure: Prettify help output

---

src/KakaduImage.cc

The global variable logfile is already declared in the .h file.
Signed-off-by: Stefan Weil <sw@weilnetz.de>

kakadu: Remove unneeded "extern" statement

---

src/IIIF.cc
src/Main.cc

In some cases, having IIP behind a proxy service or URL rewriter will cause IIP to write an ID that does not match the request URI. This breaks IIIF compatibility, since it means that a manifest may return an `@id` property that is different from the request URI.
This commit adds the ability to set a custom IIIF header that will control the URI that is reflected as the IIIF Image info ID. With X-IIIF-ID, a proxy can pass along a request URI that will be used as the URI for the `@id` property in the image info service.
This pull request also contains a formatting commit to ensure proper indentation levels and remove mixed tabs and spaces on `IIIF.cc`.

Custom header for IIIF Image IDs

---

src/IIIF.cc

During the resolving https://github.com/ruven/iipsrv/issues/77 (https://github.com/ruven/iipsrv/commit/624e02bafa429c0955d0f30a38195fd028d16958) there occurred two problems:
On the basis of which `maintain_aspect` some IIIF requests have begun processing internally with command `JTL` instead of `CVT`. `JTL` worked with compressed image but  `gray filter` needs a bitmap, so in this pull-request I made change for getting image without compression. This resolves https://github.com/ruven/iipsrv/issues/87.
Another problem is in case this request  
```
{scheme}://{server}{/prefix}/{identifier}/67352ccc-d1b0-11e1-89ae-279075081939/0,0,1,1/256,/0/default.jpg 
```
I want region of size of 1 pixel expanded to tile of size of 256 pixels, but I get something like that:
I think this type of request …

fix IIIF invalid jpeg in gray quality and IIIF region request

---

README
configure.ac
src/CVT.cc
src/Compressor.h
src/Environment.h
src/IIIF.cc
src/JPEGCompressor.cc
src/JPEGCompressor.h
src/JTL.cc
src/Main.cc
src/Makefile.am
src/PNGCompressor.cc
src/PNGCompressor.h
src/RawTile.h
src/Task.cc
src/Task.h
src/TileManager.cc
src/TileManager.h

Added support for PNG output for IIIF, two new server side controls for PNG quality (filter type) and zlib compression level.  Built support for QLT command when output is PNG but that won't get called until a PTL command is added to the IIP protocol and unrevised implementation of Compress() in PNGCompressor.cc

Add PNG output support for IIIF compliance

---

README
src/CVT.cc
src/Filters.cc
src/Filters.h
src/Makefile.am
src/RawTile.h
src/Transforms.cc
src/Transforms.h

The Lanczos filter provides an improvement in visual quality as compared
to the bilinear filter. It seems to provide more sharpess where
sharpness is needed and is not that much slower than the bilinear filter.
It runs between 75-80% as fast as the default bilinear filter.

Added Lanczos resizing filter

---

README
src/CVT.cc
src/Environment.h
src/Main.cc
src/Task.h

Added OVERSAMPLING_FACTOR as a configurable option (defaults to 1) with permitted values 1,2,3,4.   When > 1, CVT will attempt to use a tile size that is N times as large as the requested output. This generally leads to higher image quality in the output tile regardless of the resampling algorithm used although depending on the resampling algorithm, this might create more aliasing / sharpness than is desirable.  The sweet spot for the bilinear filter seems to be around 2.  The end user should experiment with combinations of resampling filters and the oversampling factor to achieve the desired quality.

Added configuration to allow CVT to oversample from larger tiles

---

src/CVT.cc
src/JPEGCompressor.cc
src/JPEGCompressor.h

Currently, XMP metadata from a source TIFF or PTIF file is copied into a 'CVT' jpeg, but the data will not be exposed by standard readers because it lacks the correct marker and ID.

add correct prefix and marker when echoing XMP metadata into CVT jpeg

---

src/Main.cc

It currently errors out on FGX_ calls. This patch is sufficient to make
requests like the following one to work without a HTTP server
MAX_CVT=3000 JPEG_QUALITY=50 MAX_IMAGE_CACHE_SIZE=10 LOGFILE=/dev/stderr VERBOSITY=5  ./src/iipsrv.fcgi "iiif=3281G028358.jp2/full/1500,/0/default.jpg"

Fix compilation with -DDEBUG enabled

---

src/OpenJPEGImage.cc

https://github.com/uclouvain/openjpeg/issues/1006 describe in length a current
implementation issue of opj_set_decode_area() combined with
opj_set_decoded_resolution_factor()
Currently, with all openjpeg 2.X, decoding a subwindow of a tiled JPEG2000 image
at a lower resolution results in a corrupted result: only the top-left part of
the output image is filled, due to some tiles not being decoded.
With current openjpeg master, up to https://github.com/uclouvain/openjpeg/commit/5a4a10120a648848de7522245f8671c3ce285dbc,
which implements more efficient sub-tile decoding,
decoding a subwindow of a single-tiled JPEG2000 image at a lower resolution
results in a corrupted image due to some code-blocks not being decoded.
This commit enables IIPRV to work with currently released openjpeg 2.X …

OpenJPEG backend: fix misuse of opj_set_decode_area() API

---

src/KakaduImage.cc
src/TileManager.cc
src/Transforms.cc

Hello, 
I had an integer overflow in the getRegion() method of the TileManager.cc file with the following values.
width : 14240
height : 13395
My in.dataLength was 35363488 because the width*height*channel*bpc was greater than INT_LIMIT before dividing by 8.
So I add parenthesis in each location than I found.
Have a nice day !

divide before multiply to avoid overflow

---

src/IIIF.cc

When the maxWidth and maxHeight parameters were added to the info.json response, the number of scaleFactors was also adjusted to be set to maxWidth/Height, and not to the actual width and height of the image. 
This had a significant performance regression on image requests in IIIF viewers. Since viewers can actually request images as tiles up to the full width and height, but the `scaleFactors` array assumed it was only up to `maxWidth` or `maxHeight`, the size of tiles requested were very small, and thus slowed down image loading. 
Two videos illustrate this. First, with the 'correct' scale factors:
https://www.dropbox.com/s/biaxchvq0ylipoy/fast-loading-no-max.mov?dl=0
and then with the `scaleFactors` constrained to a maxWidth/Height of 1000: …

Fixed: Correct scale factors

---

src/Zoomify.cc

Fix incorrect NUMTILES value in ImageProperties.xml
To be compatible with the official zoomify generator, NUMTILES
has to be the total number of tiles in all zoom levels.
Fixes #86

Zoomify: Fix invalid number of tiles (NUMTILES)

---

src/Logger.h

Hello,
In the project I am working with now I have a cluster of iipimage servers. I collect logs from these instances with Logstash. I needed a way to distinguish logs entries from individual instances in my cluster. I found that it could be done by including PID in every Syslog entry.
Regards.

Added PID with each syslog message

---

src/KakaduImage.cc

The preprocessor directive failed to compile with Kakadu 8.0.3 because the minor version was looking for >= 8. This changes it so that version 8+ is recognized as a valid 7.8+ version.

Fixed: Compile with Kakadu > 8.0.0

---

src/View.cc

No particular error was raised with this bug, but I think the wrong size variable was used in the calculation of the dimension value.

Fixed: Wrong parameter in calculation

---

src/View.cc

Previously `resolution` was not reset on subsequent calls to `calculateResolution` leading to problems where it was using a previously calculated value for a different dimension.
This fixes it by moving the `resolution` reset to inside the calculateResolution method to ensure it always starts at 0.
Fixes #189

Fixed: Reset resolution when calculate resolution is called

---

src/IIIF.cc

The correct profile value for IIIFv2 service blocks includes the ".json" suffix for the
profile document (See the example given at https://iiif.io/api/image/2.1/#profile-description).

Fixed: Correct profile value for IIIFv2
